/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cifrador */

#ifndef _Included_Cifrador
#define _Included_Cifrador
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Cifrador
 * Method:    cifrarCesar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Cifrador_cifrarCesar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Cifrador
 * Method:    descifrarCesar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Cifrador_descifrarCesar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Cifrador
 * Method:    cifrarEscitala
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Cifrador_cifrarEscitala
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Cifrador
 * Method:    descifrarEscitala
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Cifrador_descifrarEscitala
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif

