/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ejemplojni_lib_JavaCifrador */

#ifndef _Included_ejemplojni_lib_JavaCifrador
#define _Included_ejemplojni_lib_JavaCifrador
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ejemplojni_lib_JavaCifrador
 * Method:    cifrarCesar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ejemplojni_lib_JavaCifrador_cifrarCesar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ejemplojni_lib_JavaCifrador
 * Method:    descifrarCesar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ejemplojni_lib_JavaCifrador_descifrarCesar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ejemplojni_lib_JavaCifrador
 * Method:    cifrarEscitala
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ejemplojni_lib_JavaCifrador_cifrarEscitala
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ejemplojni_lib_JavaCifrador
 * Method:    descifrarEscitala
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ejemplojni_lib_JavaCifrador_descifrarEscitala
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
